var servants = [ { name: "Mash Kyrielight",					id:"1", class:0 },
	{ name: "Altria Pendragon",								id:"2", class:1},
	{ name: "Altria Pendragon (Alter)",						id:"3", class:1},
	{ name: "Altria Pendragon (Lily)",						id:"4", class:1},
	{ name: "Nero Claudius",								id:"5", class:1},
	{ name: "Siegfried",									id:"6", class:1},
	{ name: "Gaius Julius Caesar",							id:"7", class:1},
	{ name: "Attila the Hun / Altera",						id:"8", class:1},
	{ name: "Gilles de Rais",								id:"9", class:1},
	{ name: "Chevalier d'Eon",								id:"10", class:1},
	{ name: "EMIYA",										id:"11", class:2},
	{ name: "Gilgamesh",									id:"12", class:2},
	{ name: "Robin Hood",									id:"13", class:2},
	{ name: "Atalante",										id:"14", class:2},
	{ name: "Euryale",										id:"15", class:2},
	{ name: "Arash",										id:"16", class:2},
	{ name: "Cu Chulainn",									id:"17", class:3},
	{ name: "Elizabeth Bathory",							id:"18", class:3},
	{ name: "Benkei",										id:"19", class:3},
	{ name: "Cu Chulainn (Prototype)",						id:"20", class:3},
	{ name: "Leonidas I",									id:"21", class:3},
	{ name: "Romulus",										id:"22", class:3},
	{ name: "Medusa",										id:"23", class:4},
	{ name: "Georgios",										id:"24", class:4},
	{ name: "Edward Teach",									id:"25", class:4},
	{ name: "Boudicca",										id:"26", class:4},
	{ name: "Ushiwakamaru",									id:"27", class:4},
	{ name: "Alexander",									id:"28", class:4},
	{ name: "Marie Antoinette",								id:"29", class:4},
	{ name: "Martha",										id:"30", class:4},
	{ name: "Medea",										id:"31", class:5},
	{ name: "Gilles de Rais",								id:"32", class:5},
	{ name: "Hans Christian Andersen",						id:"33", class:5},
	{ name: "William Shakespeare",							id:"34", class:5},
	{ name: "Mephistopheles",								id:"35", class:5},
	{ name: "Wolfgang Amadeus Mozart",						id:"36", class:5},
	{ name: "Zhuge Liang / Lord El-Melloi II",				id:"37", class:5},
	{ name: "Cu Chulainn",									id:"38", class:5},
	{ name: "Sasaki Kojiro",								id:"39", class:6},
	{ name: "Hassan of the Cursed Arm",						id:"40", class:6},
	{ name: "Stheno",										id:"41", class:6},
	{ name: "Jing Ke",										id:"42", class:6},
	{ name: "Charles-Henri Sanson",							id:"43", class:6},
	{ name: "Phantom of the Opera",							id:"44", class:6},
	{ name: "Mata Hari",									id:"45", class:6},
	{ name: "Carmilla",										id:"46", class:6},
	{ name: "Heracles",										id:"47", class:7},
	{ name: "Lancelot",										id:"48", class:7},
	{ name: "Lu Bu Fengxian",								id:"49", class:7},
	{ name: "Spartacus",									id:"50", class:7},
	{ name: "Sakata Kintoki",								id:"51", class:7},
	{ name: "Vlad III",										id:"52", class:7},
	{ name: "Asterios",										id:"53", class:7},
	{ name: "Caligula",										id:"54", class:7},
	{ name: "Darius III",									id:"55", class:7},
	{ name: "Kiyohime",										id:"56", class:7},
	{ name: "Eric Bloodaxe",								id:"57", class:7},
	{ name: "Tamamo Cat",									id:"58", class:7},
	{ name: "Jeanne d'Arc",									id:"59", class:8},
	{ name: "Orion & Artemis",								id:"60", class:2},
	{ name: "Elizabeth Bathory (Halloween)",				id:"61", class:5},
	{ name: "Tamamo no Mae",								id:"62", class:5},
	{ name: "David",										id:"63", class:2},
	{ name: "Hector",										id:"64", class:3},
	{ name: "Francis Drake",								id:"65", class:4},
	{ name: "Mary Read",									id:"66", class:4},
	{ name: "Medea (Lily)",									id:"67", class:5},
	{ name: "Okita Soji",									id:"68", class:1},
	{ name: "Oda Nobunaga",									id:"69", class:2},
	{ name: "Scathach",										id:"70", class:3},
	{ name: "Diarmuid Ua Duibhne",							id:"71", class:3},
	{ name: "Fergus mac Roich",								id:"72", class:1},
	{ name: "Altria Pendragon (Santa Alter)",				id:"73", class:4},
	{ name: "Nursery Rhyme", 								id:"74", class:5},
	{ name: "Jack the Ripper", 								id:"75", class:6},
	{ name: "Mordred", 										id:"76", class:1},
	{ name: "Nikola Tesla", 								id:"77", class:2},
	{ name: "Altria Pendragon (Alter)", 					id:"78", class:3},
	{ name: "Paracelsus von Hohenheim", 					id:"79", class:5},
	{ name: "Charles Babbage", 								id:"80", class:5},
	{ name: "Henry Jekyll & Hyde", 							id:"81", class:6},
	{ name: "Frankenstein's Monster", 						id:"82", class:7},
	{ name: "Solomon (False)", 								id:"83", class:5},
	{ name: "Arjuna", 										id:"84", class:2},
	{ name: "Karna", 										id:"85", class:3},
	{ name: "Mysterious Heroine X", 						id:"86", class:6},
	{ name: "Fionn mac Cumhaill", 							id:"87", class:3},
	{ name: "Brynhildr", 									id:"88", class:3},
	{ name: "Beowulf", 										id:"89", class:7},
	{ name: "Nero Claudius (Bride)", 						id:"90", class:1},
	{ name: "Ryogi Shiki", 									id:"91", class:1},
	{ name: "Ryogi Shiki", 									id:"92", class:6},
	{ name: "Amakusa Shirou", 								id:"93", class:8},
	{ name: "Astolfo", 										id:"94", class:4},
	{ name: "Kid Gil", 										id:"95", class:2},
	{ name: "Edmond Dantes", 								id:"96", class:9},
	{ name: "Nightingale", 									id:"97", class:7},
	{ name: "Cu Chulainn (Alter)", 							id:"98", class:7},
	{ name: "Queen Medb", 									id:"99", class:4},
	{ name: "Helena Blavatsky", 							id:"100", class:5},
	{ name: "Rama", 										id:"101", class:1},
	{ name: "Li Shuwen", 									id:"102", class:3},
	{ name: "Thomas Edison", 								id:"103", class:5},
	{ name: "Geronimo", 									id:"104", class:5},
	{ name: "Billy the Kid", 								id:"105", class:2},
	{ name: "Jeanne d'Arc (Alter)", 						id:"106", class:9},
	{ name: "Angra Mainyu", 								id:"107", class:9},
	{ name: "Iskandar",										id:"108", class:4},
	{ name: "EMIYA", 										id:"109", class:6},
	{ name: "Hassan of the Hundred Faces", 					id:"110", class:6},
	{ name: "Irisviel / Dress of Heaven", 					id:"111", class:5},
	{ name: "Shuten Doji", 									id:"112", class:6},
	{ name: "Xuanzang Sanzang", 							id:"113", class:5},
	{ name: "Minamoto no Raikou",							id:"114", class:7},
	{ name: "Sakata Kintoki", 								id:"115", class:4},
	{ name: "Ibaraki Doji", 								id:"116", class:7},
	{ name: "Fuma Kotaro", 									id:"117", class:6},
	{ name: "Ozymandias",									id:"118", class:4},
	{ name: "Altria Pendragon", 							id:"119", class:3},
	{ name: "Nitocris", 									id:"120", class:5},
	{ name: "Lancelot", 									id:"121", class:1},
	{ name: "Tristan", 										id:"122", class:2},
	{ name: "Gawain", 										id:"123", class:1},
	{ name: "Hassan of the Serenity",						id:"124", class:6},
	{ name: "Tawara Tota", 									id:"125", class:2},
	{ name: "Bedivere", 									id:"126", class:1},
	{ name: "Leonardo Da Vinci", 							id:"127", class:5},
	{ name: "Tamamo no Mae (Summer)", 						id:"128", class:3},
	{ name: "Altria Pendragon (Summer)", 					id:"129", class:2},
	{ name: "Marie Antoinette (Summer)", 					id:"130", class:5},
	{ name: "Anne Bonny", 									id:"131", class:2},
	{ name: "Mordred (Summer)", 							id:"132", class:4},
	{ name: "Scathach (Summer)", 							id:"133", class:6},
	{ name: "Kiyohime (Summer)", 							id:"134", class:3},
	{ name: "Martha (Summer)", 								id:"135", class:8},
	{ name: "Illyasviel von Einzbern", 						id:"136", class:5},
	{ name: "Chloe von Einzbern", 							id:"137", class:2},
	{ name: "Elizabeth Bathory (Brave)", 					id:"138", class:1},
	{ name: "Cleopatra", 									id:"139", class:6},
	{ name: "Vlad III (EXTRA)", 							id:"140", class:3},
	{ name: "Jeanne d'Arc Alter Santa Lily", 				id:"141", class:3},
	{ name: "Ishtar", 										id:"142", class:2},
	{ name: "Enkidu", 										id:"143", class:3},
	{ name: "Quetzalcoatl", 								id:"144", class:4},
	{ name: "Gilgamesh", 									id:"145", class:5},
	{ name: "Medusa (Lily)", 								id:"146", class:3},
	{ name: "Gorgon", 										id:"147", class:9},
	{ name: "Jaguar Man", 									id:"148", class:3},
	{ name: "Tiamat", 										id:"149", class:14},
	{ name: "Merlin", 										id:"150", class:5},
	{ name: "Goetia", 										id:"151", class:14},
	{ name: "Solomon", 										id:"152", class:5},
	{ name: "Miyamoto Musashi", 							id:"153", class:1},
	{ name: "The Old Man of the Mountain / King Hassan", 	id:"154", class:6},
	{ name: "Mysterious Heroine X (Alter)", 				id:"155", class:7},
	{ name: "James Moriarty", 								id:"156", class:2},
	{ name: "EMIYA (Alter)", 								id:"157", class:2},
	{ name: "Hessian Lobo", 								id:"158", class:9},
	{ name: "Yan Qing", 									id:"159", class:6},
	{ name: "Arthur Pendragon", 							id:"160", class:1},
];