var servants = [ { name: "Mash Kyrielight",					id:"1", class:0,	tags:"mash fgo"},
	{ name: "Altria Pendragon",								id:"2", class:1,	tags:"altria saberface fsn zero fgo extella extellalink"},
	{ name: "Altria Pendragon (Alter)",						id:"3", class:1,	tags:"altria saberface fsn fgo"},
	{ name: "Altria Pendragon (Lily)",						id:"4", class:1,	tags:"altria saberface lily fsn fgo"},
	{ name: "Nero Claudius",								id:"5", class:1,	tags:"nero saberface extra ccc fgo extella extellalink rome"},
	{ name: "Siegfried",									id:"6", class:1,	tags:"apocrypha fgo"},
	{ name: "Gaius Julius Caesar",							id:"7", class:1,	tags:"fgo rome"},
	{ name: "Attila the Hun / Altera",						id:"8", class:1,	tags:"fgo extella extellalink"},
	{ name: "Gilles de Rais",								id:"9", class:1,	tags:"fgo apocrypha"},
	{ name: "Chevalier d'Eon",								id:"10", class:1,	tags:"fgo france"},
	{ name: "EMIYA",										id:"11", class:2,	tags:"fgo fsn extra ccc extella extella link"},
	{ name: "Gilgamesh",									id:"12", class:2,	tags:"fgo fsn zero ccc extella extellalink strangefake"},
	{ name: "Robin Hood",									id:"13", class:2,	tags:"fgo extra ccc extellalink"},
	{ name: "Atalante",										id:"14", class:2,	tags:"fgo apocrypha"},
	{ name: "Euryale",										id:"15", class:2,	tags:"fgo hollowataraxia"},
	{ name: "Arash",										id:"16", class:2,	tags:"fgo"},
	{ name: "Cu Chulainn",									id:"17", class:3,	tags:"fgo fsn extra extellalink samurairemnant"},
	{ name: "Elizabeth Bathory",							id:"18", class:3,	tags:"fgo ccc extella extellalink"},
	{ name: "Benkei",										id:"19", class:3,	tags:"fgo"},
	{ name: "Cu Chulainn (Prototype)",						id:"20", class:3,	tags:"fgo prototype"},
	{ name: "Leonidas I",									id:"21", class:3,	tags:"fgo"},
	{ name: "Romulus",										id:"22", class:3,	tags:"fgo rome"},
	{ name: "Medusa",										id:"23", class:4,	tags:"fgo fsn extella extellalink"},
	{ name: "Georgios",										id:"24", class:4,	tags:"fgo"},
	{ name: "Edward Teach",									id:"25", class:4,	tags:"fgo"},
	{ name: "Boudicca",										id:"26", class:4,	tags:"fgo"},
	{ name: "Ushiwakamaru",									id:"27", class:4,	tags:"fgo"},
	{ name: "Alexander",									id:"28", class:4,	tags:"fgo"},
	{ name: "Marie Antoinette",								id:"29", class:4,	tags:"fgo"},
	{ name: "Martha",										id:"30", class:4,	tags:"fgo"},
	{ name: "Medea",										id:"31", class:5,	tags:"fgo fsn"},
	{ name: "Gilles de Rais",								id:"32", class:5,	tags:"fgo zero extellalink"},
	{ name: "Hans Christian Andersen",						id:"33", class:5,	tags:"fgo ccc"},
	{ name: "William Shakespeare",							id:"34", class:5,	tags:"fgo apocrypha"},
	{ name: "Mephistopheles",								id:"35", class:5,	tags:"fgo"},
	{ name: "Wolfgang Amadeus Mozart",						id:"36", class:5,	tags:"fgo"},
	{ name: "Zhuge Liang / Lord El-Melloi II",				id:"37", class:5,	tags:"fgo zero casefiles"},
	{ name: "Cu Chulainn",									id:"38", class:5,	tags:"fgo"},
	{ name: "Sasaki Kojiro",								id:"39", class:6,	tags:"fgo fsn"},
	{ name: "Hassan of the Cursed Arm",						id:"40", class:6,	tags:"fgo fsn hassan"},
	{ name: "Stheno",										id:"41", class:6,	tags:"fgo"},
	{ name: "Jing Ke",										id:"42", class:6,	tags:"fgo"},
	{ name: "Charles-Henri Sanson",							id:"43", class:6,	tags:"fgo"},
	{ name: "Phantom of the Opera",							id:"44", class:6,	tags:"fgo"},
	{ name: "Mata Hari",									id:"45", class:6,	tags:"fgo"},
	{ name: "Carmilla",										id:"46", class:6,	tags:"fgo"},
	{ name: "Heracles",										id:"47", class:7,	tags:"fgo fsn"},
	{ name: "Lancelot",										id:"48", class:7,	tags:"fgo zero extellalink"},
	{ name: "Lu Bu Fengxian",								id:"49", class:7,	tags:"fgo extra extella extellalink"},
	{ name: "Spartacus",									id:"50", class:7,	tags:"fgo apocrypha"},
	{ name: "Sakata Kintoki",								id:"51", class:7,	tags:"fgo"},
	{ name: "Vlad III",										id:"52", class:7,	tags:"fgo apocrypha"},
	{ name: "Asterios",										id:"53", class:7,	tags:"fgo"},
	{ name: "Caligula",										id:"54", class:7,	tags:"fgo"},
	{ name: "Darius III",									id:"55", class:7,	tags:"fgo extellalink"},
	{ name: "Kiyohime",										id:"56", class:7,	tags:"fgo"},
	{ name: "Eric Bloodaxe",								id:"57", class:7,	tags:"fgo"},
	{ name: "Tamamo Cat",									id:"58", class:7,	tags:"fgo"},
	{ name: "Jeanne d'Arc",									id:"59", class:8,	tags:"fgo apocrypha extella extellalink"},
	{ name: "Orion & Artemis",								id:"60", class:2},
	{ name: "Elizabeth Bathory (Halloween)",				id:"61", class:5},
	{ name: "Tamamo no Mae",								id:"62", class:5},
	{ name: "David",										id:"63", class:2},
	{ name: "Hector",										id:"64", class:3},
	{ name: "Francis Drake",								id:"65", class:4},
	{ name: "Mary Read",									id:"66", class:4},
	{ name: "Medea (Lily)",									id:"67", class:5},
	{ name: "Okita Soji",									id:"68", class:1},
	{ name: "Oda Nobunaga",									id:"69", class:2},
	{ name: "Scathach",										id:"70", class:3},
	{ name: "Diarmuid Ua Duibhne",							id:"71", class:3},
	{ name: "Fergus mac Roich",								id:"72", class:1},
	{ name: "Altria Pendragon (Santa Alter)",				id:"73", class:4},
	{ name: "Nursery Rhyme", 								id:"74", class:5},
	{ name: "Jack the Ripper", 								id:"75", class:6},
	{ name: "Mordred", 										id:"76", class:1},
	{ name: "Nikola Tesla", 								id:"77", class:2},
	{ name: "Altria Pendragon (Lancer) (Alter)", 			id:"78", class:3},
	{ name: "Paracelsus von Hohenheim", 					id:"79", class:5},
	{ name: "Charles Babbage", 								id:"80", class:5},
	{ name: "Henry Jekyll & Hyde", 							id:"81", class:6},
	{ name: "Frankenstein's Monster", 						id:"82", class:7},
	{ name: "Solomon (False)", 								id:"83", class:5},
	{ name: "Arjuna", 										id:"84", class:2},
	{ name: "Karna", 										id:"85", class:3},
	{ name: "Mysterious Heroine X", 						id:"86", class:6},
	{ name: "Fionn mac Cumhaill", 							id:"87", class:3},
	{ name: "Brynhildr", 									id:"88", class:3},
	{ name: "Beowulf", 										id:"89", class:7},
	{ name: "Nero Claudius (Bride)", 						id:"90", class:1},
	{ name: "Ryogi Shiki", 									id:"91", class:1},
	{ name: "Ryogi Shiki", 									id:"92", class:6},
	{ name: "Amakusa Shirou", 								id:"93", class:8},
	{ name: "Astolfo", 										id:"94", class:4},
	{ name: "Kid Gil", 										id:"95", class:2},
	{ name: "Edmond Dantes", 								id:"96", class:9},
	{ name: "Nightingale", 									id:"97", class:7},
	{ name: "Cu Chulainn (Alter)", 							id:"98", class:7},
	{ name: "Queen Medb", 									id:"99", class:4},
	{ name: "Helena Blavatsky", 							id:"100", class:5},
	{ name: "Rama", 										id:"101", class:1},
	{ name: "Li Shuwen", 									id:"102", class:3},
	{ name: "Thomas Edison", 								id:"103", class:5},
	{ name: "Geronimo", 									id:"104", class:5},
	{ name: "Billy the Kid", 								id:"105", class:2},
	{ name: "Jeanne d'Arc (Alter)", 						id:"106", class:9},
	{ name: "Angra Mainyu", 								id:"107", class:9},
	{ name: "Iskandar",										id:"108", class:4},
	{ name: "EMIYA", 										id:"109", class:6},
	{ name: "Hassan of the Hundred Faces", 					id:"110", class:6},
	{ name: "Irisviel / Dress of Heaven", 					id:"111", class:5},
	{ name: "Shuten Doji", 									id:"112", class:6},
	{ name: "Xuanzang Sanzang", 							id:"113", class:5},
	{ name: "Minamoto no Raikou",							id:"114", class:7},
	{ name: "Sakata Kintoki", 								id:"115", class:4},
	{ name: "Ibaraki Doji", 								id:"116", class:7},
	{ name: "Fuma Kotaro", 									id:"117", class:6},
	{ name: "Ozymandias",									id:"118", class:4},
	{ name: "Altria Pendragon (Lancer)",					id:"119", class:3},
	{ name: "Nitocris", 									id:"120", class:5},
	{ name: "Lancelot", 									id:"121", class:1},
	{ name: "Tristan", 										id:"122", class:2},
	{ name: "Gawain", 										id:"123", class:1},
	{ name: "Hassan of the Serenity",						id:"124", class:6},
	{ name: "Tawara Tota", 									id:"125", class:2},
	{ name: "Bedivere", 									id:"126", class:1},
	{ name: "Leonardo Da Vinci", 							id:"127", class:5},
	{ name: "Tamamo no Mae (Summer)", 						id:"128", class:3},
	{ name: "Altria Pendragon (Summer)", 					id:"129", class:2},
	{ name: "Marie Antoinette (Summer)", 					id:"130", class:5},
	{ name: "Anne Bonny", 									id:"131", class:2},
	{ name: "Mordred (Summer)", 							id:"132", class:4},
	{ name: "Scathach (Summer)", 							id:"133", class:6},
	{ name: "Kiyohime (Summer)", 							id:"134", class:3},
	{ name: "Martha (Summer)", 								id:"135", class:8},
	{ name: "Illyasviel von Einzbern", 						id:"136", class:5},
	{ name: "Chloe von Einzbern", 							id:"137", class:2},
	{ name: "Elizabeth Bathory (Brave)", 					id:"138", class:1},
	{ name: "Cleopatra", 									id:"139", class:6},
	{ name: "Vlad III (EXTRA)", 							id:"140", class:3},
	{ name: "Jeanne d'Arc Alter Santa Lily", 				id:"141", class:3},
	{ name: "Ishtar", 										id:"142", class:2},
	{ name: "Enkidu", 										id:"143", class:3},
	{ name: "Quetzalcoatl", 								id:"144", class:4},
	{ name: "Gilgamesh", 									id:"145", class:5},
	{ name: "Medusa (Lily)", 								id:"146", class:3},
	{ name: "Gorgon", 										id:"147", class:9},
	{ name: "Jaguar Man", 									id:"148", class:3},
	{ name: "Beast II Tiamat", 								id:"149", class:14},
	{ name: "Merlin", 										id:"150", class:5},
	{ name: "Beast I Goetia", 								id:"151", class:14},
	{ name: "Solomon", 										id:"152", class:5},
	{ name: "Miyamoto Musashi", 							id:"153", class:1},
	{ name: "The Old Man of the Mountain / King Hassan", 	id:"154", class:6},
	{ name: "Mysterious Heroine X (Alter)", 				id:"155", class:7},
	{ name: "James Moriarty", 								id:"156", class:2},
	{ name: "EMIYA (Alter)", 								id:"157", class:2},
	{ name: "Hessian Lobo", 								id:"158", class:9},
	{ name: "Yan Qing", 									id:"159", class:6},
	{ name: "Arthur Pendragon", 							id:"160", class:1},
	{ name: "Hijikata Toshizo", 							id:"161", class:7},
	{ name: "Chacha", 										id:"162", class:7},
	{ name: "Meltryllis", 									id:"163", class:11},
	{ name: "Passionlip", 									id:"164", class:11},
	{ name: "Suzuka Gozen",									id:"165", class:1},
	{ name: "BB",											id:"166", class:10},
	{ name: "Sesshoin Kiara",								id:"167", class:11},
	{ name: "Beast III/R Heaven's Hole",					id:"168", class:14},
	{ name: "Scheherazade",									id:"169", class:5},
	{ name: "Wu Zetian",									id:"170", class:6},
	{ name: "Penthesilea",									id:"171", class:7},
	{ name: "Christopher Columbus",							id:"172", class:4},
	{ name: "Sherlock Holmes",								id:"173", class:8},
	{ name: "Paul Bunyan",									id:"174", class:7},
	{ name: "Nero Claudius (Summer)",						id:"175", class:5},
	{ name: "Frankenstein's Monster (Summer)",				id:"176", class:1},
	{ name: "Nitocris (Summer)",							id:"177", class:6},
	{ name: "Oda Nobunaga (Summer)",						id:"178", class:7},
	{ name: "Altria Pendragon (Alter) (Summer)",			id:"179", class:4},
	{ name: "Helena Blavatsky (Summer)",					id:"180", class:2},
	{ name: "Minamoto no Raikou (Summer)",					id:"181", class:3},
	{ name: "Ishtar (Summer)",								id:"182", class:4},
	{ name: "Parvati",										id:"183", class:3},
	{ name: "Tomoe Gozen",									id:"184", class:2},
	{ name: "Mochizuki Chiyome",							id:"185", class:6},
	{ name: "Hozoin Inshun",								id:"186", class:3},
	{ name: "Yagyu Tajima no Kami Munenori",				id:"187", class:1},
	{ name: "Kato Danzo",									id:"188", class:6},
	{ name: "Osakabehime",									id:"189", class:6},
	{ name: "Mecha Eli-chan",								id:"190", class:11},
	{ name: "Mecha Eli-chan Mk. II",						id:"191", class:11},
	{ name: "Circe",										id:"192", class:5},
	{ name: "Nezha",										id:"193", class:3},
	{ name: "Queen of Sheba",								id:"194", class:5},
	{ name: "Abigail Williams",								id:"195", class:12},
	{ name: "Ereshkigal",									id:"196", class:3},
	{ name: "Altera the Sun(ta)",							id:"197", class:2},
	{ name: "Katsushika Hokusai",							id:"198", class:12},
	{ name: "Semiramis",									id:"199", class:6},
	{ name: "Asagami Fujino",								id:"200", class:2},
	{ name: "Anastasia",									id:"201", class:5},
	{ name: "Atalante (Alter)",								id:"202", class:7},
	{ name: "Avicebron",									id:"203", class:5},
	{ name: "Antonio Salieri",								id:"204", class:9},
	{ name: "Ivan the Terrible",							id:"205", class:4},
	{ name: "Achilles",										id:"206", class:4},
	{ name: "Chiron",										id:"207", class:2},
	{ name: "Sieg",											id:"208", class:5},
	{ name: "Okita Soji (Alter)",							id:"209", class:11},
	{ name: "Okada Izou",									id:"210", class:6},
	{ name: "Sakamoto Ryoma",								id:"211", class:4},
	{ name: "Napoleon",										id:"212", class:2},
	{ name: "Sigurd",										id:"213", class:1},
	{ name: "Valkyrie",										id:"214", class:3},
	{ name: "Scathach-Skadi",								id:"215", class:5},
	{ name: "Jeanne d'Arc (Summer)",						id:"216", class:2},
	{ name: "Ibaraki Doji (Summer)",						id:"217", class:3},
	{ name: "Ushiwakamaru (Summer)",						id:"218", class:6},
	{ name: "Jeanne d'Arc (Alter) (Summer)",				id:"219", class:7},
	{ name: "BB (Summer)",									id:"220", class:10},
	{ name: "Queen Medb (Summer)",							id:"221", class:1},
	{ name: "Mysterious Heroine XX (Summer)",				id:"222", class:12},
	{ name: "Diarmuid Ua Duibhne",							id:"223", class:1},
	{ name: "Sitonai",										id:"224", class:11},
	{ name: "Shuten Doji (Oni Cure)",						id:"225", class:5},
	{ name: "Xiang Yu",										id:"226", class:7},
	{ name: "Lanling Wang",									id:"227", class:1},
	{ name: "Qin Liangyu",									id:"228", class:3},
	{ name: "Shi Huang Di",									id:"229", class:8},
	{ name: "Consort Yu",									id:"230", class:6},
	{ name: "Red Hare",										id:"231", class:4},
	{ name: "Bradamante",									id:"232", class:3},
	{ name: "Quetzalcoatl (Samba Santa)",					id:"233", class:8},
	{ name: "Beni-Enma",									id:"234", class:1},
	{ name: "Li Shuwen",									id:"235", class:6},
	{ name: "Miyu Edelfelt",								id:"236", class:5},
	{ name: "Murasaki Shikibu",								id:"237", class:5},
	{ name: "Kingprotea",									id:"238", class:11},
	{ name: "Kama",											id:"239", class:6},
	{ name: "Beast III/L Mara",								id:"240", class:14},
	{ name: "Sima Yi (Reines)",								id:"241", class:4},
	{ name: "Astraea",										id:"242", class:8},
	{ name: "Gray",											id:"243", class:6},
	{ name: "Jinako Carigiri",								id:"244", class:10},
	{ name: "Lakshmibai",									id:"245", class:1},
	{ name: "William Tell",									id:"246", class:2},
	{ name: "Arjuna (Alter)",								id:"247", class:7},
	{ name: "Asvatthaman",									id:"248", class:2},
	{ name: "Asclepius",									id:"249", class:5},
	{ name: "Demon King Nobunaga",							id:"250", class:9},
	{ name: "Mori Nagayoshi",								id:"251", class:7},
	{ name: "Nagao Kagetora",								id:"252", class:3},
	{ name: "Leonardo Da Vinci (Mini)",						id:"253", class:4},
	{ name: "Jason",										id:"254", class:1},
	{ name: "Paris",										id:"255", class:2},
	{ name: "Gareth",										id:"256", class:3},
	{ name: "Bartholomew Roberts",							id:"257", class:4},
	{ name: "Chen Gong",									id:"258", class:5},
	{ name: "Charlotte Corday",								id:"259", class:6},
	{ name: "Salome",										id:"260", class:7},
	{ name: "Miyamoto Musashi (Summer)",					id:"261", class:7},
	{ name: "Osakabehime (Summer)",							id:"262", class:2},
	{ name: "Carmilla (Summer)",							id:"263", class:4},
	{ name: "Katsushika Hokusai (Summer)",					id:"264", class:1},
	{ name: "Altria Pendragon (Lancer) (Summer)",			id:"265", class:8},
	{ name: "Mysterious Alter Ego Lambda (Summer)",			id:"266", class:3},
	{ name: "Okita J Soji (Summer)",						id:"267", class:6},
	{ name: "Space Ishtar",									id:"268", class:9},
	{ name: "Calamity Jane",								id:"269", class:9},
	{ name: "Astolfo",										id:"270", class:1},
	{ name: "Nightingale (Santa)",							id:"271", class:2},
	{ name: "Super Orion",									id:"272", class:2},
	{ name: "Mandricardo",									id:"273", class:4},
	{ name: "Europa",										id:"274", class:4},
	{ name: "Yang Guifei",									id:"275", class:12},
	{ name: "Sei Shonagon",									id:"276", class:2},
	{ name: "Odysseus",										id:"277", class:4},
	{ name: "Dioscuri",										id:"278", class:1},
	{ name: "Caenis",										id:"279", class:3},
	{ name: "Romulus-Quirinus",								id:"280", class:3},
	{ name: "Voyager",										id:"281", class:12},
	{ name: "Kijyo Koyo",									id:"282", class:7},
	{ name: "Utsumi Erice",									id:"283", class:3},
	{ name: "Altria Caster",								id:"284", class:5},
	{ name: "Sesshoin Kiara (Summer)",						id:"285", class:10},
	{ name: "Illyasviel von Einzbern (Summer)",				id:"286", class:2},
	{ name: "Brynhildr (Summer)",							id:"287", class:7},
	{ name: "Consort Yu (Summer)",							id:"288", class:3},
	{ name: "Abigail Williams (Summer)",					id:"289", class:12},
	{ name: "Tomoe Gozen (Summer)",							id:"290", class:1},
	{ name: "Murasaki Shikibu (Summer)",					id:"291", class:4},
	{ name: "Himiko",										id:"292", class:8},
	{ name: "Saito Hajime",									id:"293", class:1},
	{ name: "Oda Nobukatsu",								id:"294", class:2},
	{ name: "Van Gogh",										id:"295", class:12},
	{ name: "Nemo",											id:"296", class:4},
	{ name: "Ashiya Douman",								id:"297", class:11},
	{ name: "Watanabe no Tsuna",							id:"298", class:1},
	{ name: "Ibuki Doji",									id:"299", class:1},
	{ name: "Vritra",										id:"300", class:3},
	{ name: "Karna (Santa)",								id:"301", class:1},
	{ name: "Senji Muramasa",								id:"302", class:1},
	{ name: "Taira no Kagekiyo",							id:"303", class:9},
	{ name: "Kiichi Hogen",									id:"304", class:6},
	{ name: "Amor (Caren Hortensia)",						id:"305", class:8},
	{ name: "Galatea",										id:"306", class:7},
	{ name: "Miss Crane",									id:"307", class:5},
	{ name: "Mysterious Idol X (Alter)",					id:"308", class:12},
	{ name: "Morgan",										id:"309", class:7},
	{ name: "Fairy Knight Gawain / Barghest",				id:"310", class:1},
	{ name: "Fairy Knight Tristan / Baobhan Sith",			id:"311", class:2},
	{ name: "Fairy Knight Lancelot / Melusine",				id:"312", class:3},
	{ name: "Percival",										id:"313", class:3},
	{ name: "Koyanskaya of Light",							id:"314", class:6},
	{ name: "Habetrot",										id:"315", class:4},
	{ name: "Oberon",										id:"316", class:13},
	{ name: "Okita Soji (Alter) (Summer)",					id:"317", class:1},
	{ name: "Anastasia & Viy (Summer)",						id:"318", class:2},
	{ name: "Charlotte Corday (Summer)",					id:"319", class:5},
	{ name: "Leonardo Da Vinci (Mini) (Summer)",			id:"320", class:8},
	{ name: "Kama (Summer)",								id:"321", class:9},
	{ name: "Caenis (Summer)",								id:"322", class:4},
	{ name: "Sei Shonagon (Summer)",						id:"323", class:7},
	{ name: "Jacques de Molay",								id:"324", class:12},
	{ name: "Zenobia",										id:"325", class:2},
	{ name: "Elizabeth Bathory (Cinderella)",				id:"326", class:4},
	{ name: "Izumo no Okuni",								id:"327", class:5},
	{ name: "Mysterious Ranmaru X",							id:"328", class:9},
	{ name: "Sakamoto Ryoma",								id:"329", class:3},
	{ name: "Martha (Santa)",								id:"330", class:5},
	{ name: "Taigong Wang",									id:"331", class:4},
	{ name: "Dobrynya Nikitich",							id:"332", class:4},
	{ name: "Beast IV Lost Koyanskaya",						id:"333", class:14},
	{ name: "Koyanskaya of Darkness",						id:"334", class:12},
	{ name: "\"Hephastion\" / Faker",						id:"335", class:13},
	{ name: "Manannan mac Lir (Bazett Fraga McRemitz)",		id:"336", class:11},
	{ name: "Trung Sisters",								id:"337", class:1},
	{ name: "Taisui Xingjun",								id:"338", class:11},
	{ name: "Super Bunyan",									id:"339", class:11},
	{ name: "Daikokuten",									id:"340", class:5},
	{ name: "Mary Anning",									id:"341", class:3},
	{ name: "Constantine XI",								id:"342", class:4},
	{ name: "Charlemagne",									id:"343", class:1},
	{ name: "Roland",										id:"344", class:1},
	{ name: "Kriemhild",									id:"345", class:7},
	{ name: "James Moriarty",								id:"346", class:8},
	{ name: "Don Quixote",									id:"347", class:3},
	{ name: "Zhang Jue",									id:"348", class:5},
	{ name: "Kyokutei Bakin",								id:"349", class:4},
	{ name: "Minamoto no Tametomo",							id:"350", class:2},
	{ name: "Archetype: Earth",								id:"351", class:10},
	{ name: "Xu Fu",										id:"352", class:11},
	{ name: "Lady Avalon / Merlin (Prototype)",				id:"353", class:13},
	{ name: "Gareth (Summer)",								id:"354", class:1},
	{ name: "Ibuki Doji (Summer)",							id:"355", class:7},
	{ name: "Utsumi Erice (Summer)",						id:"356", class:9},
	{ name: "Scathach-Skadi (Summer)",						id:"357", class:8},
	{ name: "Wu Zetian (Summer)",							id:"358", class:5},
	{ name: "Thrud (Summer)",								id:"359", class:6},
	{ name: "Hildr (Summer)",								id:"360", class:6},
	{ name: "Ortlinde (Summer)",							id:"361", class:6},
	{ name: "Sen no Rikyu",									id:"362", class:7},
	{ name: "Yamanami Keisuke",								id:"363", class:1},
	{ name: "Iyo",											id:"364", class:8},
	{ name: "Huyan Zhuo",									id:"365", class:6},
	{ name: "Huang Feihu",									id:"366", class:4},
	{ name: "Nine-Tattoo Dragon Eliza",						id:"367", class:13},
	{ name: "Britomart",									id:"368", class:3},
	{ name: "Grigori Rasputin (Kotomine Kirei)",			id:"369", class:11},
	{ name: "Nitocris (Alter)",								id:"370", class:9},
	{ name: "Tezcatlipoca",									id:"371", class:6},
	{ name: "Tenochtitlan",									id:"372", class:13},
	{ name: "Kukulkan",										id:"373", class:12},
	{ name: "Popess Johanna",								id:"374", class:8},
	{ name: "Takasugi Shinsaku",							id:"375", class:2},
	{ name: "Larva Tiamat",									id:"376", class:11},
	{ name: "Sodom's Beast / Draco",						id:"377", class:14},
	{ name: "Locusta",										id:"378", class:6},
	{ name: "Setanta",										id:"379", class:1},
	{ name: "Kashin Koji",									id:"380", class:6},
	{ name: "Bhima",										id:"381", class:3},
	{ name: "Duryodhana",									id:"382", class:7},
	{ name: "Durga",										id:"383", class:2},
	{ name: "Medusa",										id:"384", class:1},
	{ name: "Aesc the Savior",								id:"385", class:5},
	{ name: "Altria Caster (Summer)",						id:"386", class:7},
	{ name: "Suzuka Gozen (Vacay)",							id:"387", class:4},
	{ name: "Chloe von Einzbern (Summer)",					id:"388", class:9},
	{ name: "Knocknarea (Summer)",							id:"389", class:12},
	{ name: "Melusine (Summer)",							id:"390", class:8},
	{ name: "UDK-Barghest (Summer)",						id:"391", class:2},
	{ name: "Cait Cu Cerpriestess (Summer)",				id:"392", class:13},
	{ name: "Wandjina",										id:"393", class:12},
	{ name: "Ptolemaios",									id:"394", class:2},
	{ name: "Sugitani Zenjubo",								id:"395", class:2},
	{ name: "Theseus",										id:"396", class:1},
	{ name: "Takeda Shingen",								id:"397", class:4},
	{ name: "Nagakura Shinpachi",							id:"398", class:7},
	{ name: "Saika Magoichi",								id:"399", class:2},
	{ name: "Uesugi Kenshin",								id:"400", class:8},
	{ name: "Nemo (Santa)",									id:"401", class:4},
	{ name: "Yamato Takeru",								id:"402", class:1},
	{ name: "Ushi Gozen",									id:"403", class:9},
	{ name: "Yui Shosetsu",									id:"404", class:5},
	{ name: "Miyamoto Iori",								id:"405", class:1},
	{ name: "Andromeda",									id:"406", class:4},
	{ name: "Marie Antoinette (Alter)",						id:"407", class:9},
	{ name: "Hassan of the Shining Star",					id:"408", class:6},
	{ name: "King of the Cavern, Monte Cristo",				id:"409", class:9},
	{ name: "Alessandro di Cagliostro",						id:"410", class:13},
	{ name: "E-Flare Marie",								id:"411", class:14},
	{ name: "E-Aqua Marie",									id:"412", class:14},
	{ name: "Aozaki Aoko",									id:"413", class:12},
	{ name: "Shizuki Sojuro",								id:"414", class:7},
	{ name: "Kuonji Alice",									id:"415", class:5},
	{ name: "Azumi no Isora (Hibiki & Chikagi)",			id:"416", class:11},
	{ name: "Space Ereshkigal",								id:"417", class:14},
	{ name: "Mysterious Executor C.I.E.L.",					id:"418", class:10},
	{ name: "Dobrynya Nikitich (Summer)",					id:"419", class:3},
	{ name: "Xu Fu (Summer)",								id:"420", class:9},
	{ name: "BB Dubai",										id:"421", class:10},
	{ name: "Tenochtitlan (Summer)",						id:"422", class:10},
	{ name: "Mysterious Heroine XX (Alter) (Summer)",		id:"423", class:12},
	{ name: "Kishinami Hakuno",								id:"424", class:10},
	{ name: "Kishinami Hakunon",							id:"425", class:10},
	{ name: "Kazuradrop",									id:"426", class:11},
	{ name: "Tutankhamun",									id:"427", class:2},
	{ name: "Van Gogh (Miner)",								id:"428", class:3},
	{ name: "Louhi",										id:"429", class:7},
	{ name: "Abigail Williams (Santa)",						id:"430", class:13},
	{ name: "Phantasmoon",									id:"431", class:13},
	{ name: "Richard I",									id:"432", class:1},
	{ name: "Biscione",										id:"433", class:3},
	{ name: "Kurohime",										id:"434", class:1},
	{ name: "Ono no Komachi",								id:"435", class:5},
	{ name: "E-Grand Marie",								id:"436", class:14},
	{ name: "Dante Alighieri",								id:"437", class:13},
	{ name: "Metatron Jeanne",								id:"438", class:8},
	{ name: "King Ashoka",									id:"439", class:3},
	{ name: "Lilith",										id:"440", class:7},
	{ name: "Typhon Ephemeros",								id:"441", class:13},
	{ name: "Indra",										id:"442", class:3},
	{ name: "E-Stellar Marie",								id:"443", class:14},
	{ name: "U-Olga Marie",									id:"444", class:14},
	{ name: "Passionlip (Summer)",							id:"445", class:1},
	{ name: "Kriemhild (Summer)",							id:"446", class:4},
	{ name: "Huyan Zhuo (Summer)",							id:"447", class:7},
	{ name: "Moon Rabbit (Summer)",							id:"448", class:10},
	{ name: "Miyu Edelfelt (Summer)",						id:"449", class:3},
	{ name: "Larva Tiamat (Summer)",						id:"450", class:2},
	{ name: "Jeunesse Crane (Summer)",						id:"451", class:11},
	{ name: "Nemo / Noah",									id:"452", class:4},
	{ name: "Kawakami Gensai",								id:"453", class:6},
	{ name: "Todo Heisuke",									id:"454", class:9},
	{ name: "Harada Sanosuke",								id:"455", class:3},
	{ name: "Kondo Isami",									id:"456", class:1},
	{ name: "Elizabeth Bathory (Perfect)",					id:"457", class:3},
	{ name: "Elizabeth of the End",							id:"458", class:9},
	{ name: "Solomon / Goetia",								id:"459", class:13},
	{ name: "Maris Chaldeas",								id:"460", class:14},
	{ name: "Lord Logres",									id:"461", class:1},
	{ name: "Hanasaka no Okina",							id:"462", class:5},
	{ name: "Hebi Nyobo",									id:"463", class:6},
	{ name: "Flora",										id:"464", class:11},
	{ name: "Demeter",										id:"465", class:3},
	{ name: "Jacques de Molay",								id:"466", class:1},
	{ name: "Francois Prelati / Francesca Prelati",			id:"467", class:5},
	{ name: "Hippolyta",									id:"468", class:4},
	{ name: "John Lackland",								id:"469", class:9},
	{ name: "Urdr",											id:"470", class:2},
	{ name: "Ascalaphus",									id:"471", class:11},
	{ name: "Gray Lily",									id:"472", class:1},
	{ name: "Gray Lily",									id:"473", class:3},
	{ name: "Hassan-i-Sabbah / Azrael",						id:"474", class:6,		tags:"fgo hassan"}
];


